Fixed Failure of Authentication message being output to stdin instead of stderr
Signed-off-by: AZMCode <adrianozambrana@protonmail.com>

diff --git a/git-credential-bw b/git-credential-bw
--- a/git-credential-bw
+++ b/git-credential-bw
@@ -60,7 +60,7 @@ get(){
 	done
 
 	if [ "$currStatus" != "unlocked" ]; then
-		echo "Could not authenticate"
+		echo "Could not authenticate" >&2
 		exit 1
 	fi
 
